// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhCI5ZK-DT8li0BLWog3PlNhCn0zGzb68',
    appId: '1:452480797141:web:92ceb0470de40354f1555c',
    messagingSenderId: '452480797141',
    projectId: 'ochat-flutterchatapp',
    authDomain: 'ochat-flutterchatapp.firebaseapp.com',
    storageBucket: 'ochat-flutterchatapp.firebasestorage.app',
    measurementId: 'G-YRS7LSWMWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP29ls4WiYlAsKwxcaqH8PleftwEFZ-Tc',
    appId: '1:452480797141:android:5a4bd5cd31f5afa9f1555c',
    messagingSenderId: '452480797141',
    projectId: 'ochat-flutterchatapp',
    storageBucket: 'ochat-flutterchatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShQSY6Izq88Pt1QWOVbY75KZXgWTyTrA',
    appId: '1:452480797141:ios:a2e8ef2ea9abb289f1555c',
    messagingSenderId: '452480797141',
    projectId: 'ochat-flutterchatapp',
    storageBucket: 'ochat-flutterchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShQSY6Izq88Pt1QWOVbY75KZXgWTyTrA',
    appId: '1:452480797141:ios:a2e8ef2ea9abb289f1555c',
    messagingSenderId: '452480797141',
    projectId: 'ochat-flutterchatapp',
    storageBucket: 'ochat-flutterchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhCI5ZK-DT8li0BLWog3PlNhCn0zGzb68',
    appId: '1:452480797141:web:4570e5feef1d0619f1555c',
    messagingSenderId: '452480797141',
    projectId: 'ochat-flutterchatapp',
    authDomain: 'ochat-flutterchatapp.firebaseapp.com',
    storageBucket: 'ochat-flutterchatapp.firebasestorage.app',
    measurementId: 'G-WKKWXF05BL',
  );
}
